version: '3'

networks:
    LEMP:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: LEMP_nginx
        ports:
            - "127.0.0.1:80:80"
        volumes:
            - ./code:/code:rw
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - LEMP

    mariaDB:
        image: mariadb:latest
        container_name: LEMP_mariaDB
        volumes:
            - ./database:/var/lib/mysql:rw
        ports:
            - "3306:3306"
        depends_on:
            - nginx
        environment:
            - MYSQL_ROOT_PASSWORD=654321
        networks:
            - LEMP

    php:
        build: .
        container_name: LEMP_php
        volumes:
            - ./code:/code
        ports:
            - "9000:9000"
        networks:
            - LEMP

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: LEMP_phpMyAdmin
        ports:
            - "8183:80"
        environment:
            PMA_ARBITRARY: 1
        depends_on:
            - mariaDB
        networks:
            - LEMP
    composer:
        image: composer/composer:alpine
        container_name: LEMP_composer
        depends_on:
            - nginx
        ports:
            - "3000:80"
        volumes:
            - ./code:/app:rw
        networks:
            - LEMP
